displayName: $agentDisplayNameYaml$
schemaName: $agentSchemaNameYaml$
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  authoringModel: CliCopilot
  recognizer:
    kind: CLICopilotRecognizer
  agentSettings:
    model:
      series: Sonnet46
    instructions:
      segments:
        - kind: StaticSegment
          value: $agentInstructionsYaml$
template: cliagent-1.0.0
language: 1033
